### PR TITLE
Adds grid movement

### PR DESCRIPTION
**Pull request by mr-winters**
Allows the use of the numpad to move in user-specified increments. Intended for use in marking polygon coordinates with 'space'.

Num0 will prompt the user for a new increment value (default 25 pixels).

Also added a ',' to the coordinate output in the console, to make it easy to paste the output into the map HTML file. (Easier to delete the last one than to add commas between the others.)

### CODE REVIEW

**Comment by mr-winters** [comment]
Just a note: I'm new to Github, so if I'm breaching some etiquette by adding/suggesting this then let me know.

**Comment by byronknoll** [comment]
Thanks, sounds good.

**Comment by byronknoll** [comment]
I submitted a new commit which changes your code a bit. Some keyboards don't have numpads, so I made the numpad keys just equivalent to normal direction keys. The speed modifier now affects all directions. Holding a key down keeps movement going, but you can choose a speed like 0.1 to make fine-tuning easier.

**Comment by mr-winters** [comment]
It's good to have speed control within the map, but the goal of the incremental movement was to allow rapid movement along a specified grid, since a significant number of maps are grid based. The mouse already covers the need for fine movement I think, although this improves on that by allowing fine orthogonal movement as well. I didn't think about the numpad thing though, that's be a problem for mac users in particular. Perhaps using shift or caps lock could toggle between grid movement and free movement? 

On the other hand. if it's just for map prep (it's not a feature that is much use for when the finished map is actually in use), maybe I should just focus on making a minor app that preps the map and polygons and outputs to html file automatically, rather than use the html file as an ad-hoc prep tool.

**Comment by byronknoll** [comment]
That makes sense. Yeah, having incremental movement seems useful. I like the idea of using shift/caps lock to toggle grid movement. I can add that tonight.

**Comment by byronknoll** [comment]
OK, I have committed code to toggle grid movement using "shift". Let me know if you have any other feature requests.

**Pull request merged**
